name: form tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
     
      - name: Cypress_run_formTests_chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cypress:run:formTests
          
      
      - name: Cypress_run_formTests_firefox
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          command: npm run cypress:run:formTests
          