name: form tests
on: push
jobs:
  cypress-run-formTest-chrome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
     
      - name: Cypress_run_formTests_chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run:formTests:chrome

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-report-chrome
          path: cypress/reports/html          
              
  cypress-run-formTest-firefox:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress_run_formTests_firefox
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run:formTests:firefox

          